
ALTER TABLE user
    DROP COLUMN name;

ALTER TABLE user
    ADD COLUMN first_name VARCHAR(255) NULL;

ALTER TABLE user
    ADD COLUMN last_name VARCHAR(255) NULL;

ALTER TABLE user
    MODIFY COLUMN username VARCHAR(255) NOT NULL UNIQUE;

ALTER TABLE user
    MODIFY COLUMN email VARCHAR(255) NOT NULL;